### ISSUE TITLE
我在测试culane时，KeyError: 'seg'

### ISSUE THREAD

**Issue by ChenSi521** [zkyseu/PPlanedet#3]
python tools/detect.py configs/condlane/resnet50_culane.py --img /data/our_testset --load_from /PPlanedet/models/resnet50_culane/model.pd --savedir ./vis
出现下面的错误：
<img width="551" alt="image" src="https://user-images.githubusercontent.com/26666273/228452504-00f28b2c-5c03-4170-904d-72c7398ce4b0.png">
dict_keys(['seeds', 'hm'])是我打印出来的 out[1].keys()，没有'seg'这个键值。

请问怎么破？

**Comment by zkyseu** [comment]
@ChenSi521 您好这个应该是程序的一个bug，我已经修复了，将detect.py中的下面函数进行修改，非常感谢哈。
```
def run(self, data,image_dir):
    img_path = copy(data)
    data = self.preprocess(data)
    out = self.inference(data)
#        data['lanes'] = out[0][0]
#        data['lanes'],seg = self.inference(data)[0],self.inference(data)[1]
    if self.cfg.show or self.cfg.savedir:
        if not self.cfg.seg:
            data['lanes'] = self.net.get_lanes(out[1])[0]
            self.show(data)
        else:
            #将seg移到这个地方即可
            seg = out[1]['seg']
            self.show_seg(seg,data,image_dir,img_path,)
    return data
```

**Comment by ChenSi521** [comment]
感谢您的及时回复！

但是我按照所说的修改后，还是不行，如下图所示：
<img width="782" alt="image" src="https://user-images.githubusercontent.com/26666273/228726439-c90dcec4-901a-4a10-92d3-9598dc9fff11.png">

同样的错误依然出现：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/26666273/228726573-1679a87a-3e42-4aa8-b40e-71958bd5162f.png">

**我猜测是这个原因：**
模型在load的时候出现了很多Skip loading。有可能是相应的参数没有加载到模型中去
```python
W0330 04:02:53.468421  5234 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0330 04:02:53.471786  5234 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:275: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float64, but right dtype is paddle.float32, the right dtype will convert to paddle.float64
  warnings.warn(
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for aggregator.attn_layers.0.pre_conv._conv.bias. aggregator.attn_layers.0.pre_conv._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for aggregator.attn_layers.0.final_conv._conv.bias. aggregator.attn_layers.0.final_conv._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for aggregator.attn_layers.1.pre_conv._conv.bias. aggregator.attn_layers.1.pre_conv._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for aggregator.attn_layers.1.final_conv._conv.bias. aggregator.attn_layers.1.final_conv._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.lateral_convs.0._conv.bias. neck.lateral_convs.0._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.lateral_convs.1._conv.bias. neck.lateral_convs.1._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.lateral_convs.2._conv.bias. neck.lateral_convs.2._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.lateral_convs.3._conv.bias. neck.lateral_convs.3._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.fpn_convs.0._conv.bias. neck.fpn_convs.0._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.fpn_convs.1._conv.bias. neck.fpn_convs.1._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.fpn_convs.2._conv.bias. neck.fpn_convs.2._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for neck.fpn_convs.3._conv.bias. neck.fpn_convs.3._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for heads.mask_branch.0._conv.bias. heads.mask_branch.0._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for heads.mask_branch.1._conv.bias. heads.mask_branch.1._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1517: UserWarning: Skip loading for heads.mask_branch.2._conv.bias. heads.mask_branch.2._conv.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
  0%|                                                                                                                  | 0/20 [00:00<?, ?it/s](1024, 3328, 3)
/opt/conda/envs/pplanetdet0/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:275: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.float64, the right dtype will convert to paddle.float32
  warnings.warn(
/mmsegmentation/data/lane_detection/PPlanedet/PPlanedet/pplanedet/model/heads/condlane.py:895: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  poses, np.long)).astype('int64').unsqueeze(1)
  0%|                                                                                                                  | 0/20 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "tools/detect.py", line 202, in <module>
    process(args)
  File "tools/detect.py", line 191, in process
    detect.run(p,args.img)
  File "tools/detect.py", line 167, in run
    seg= out[1]['seg']
KeyError: 'seg'
```

我的paddle是2.4.1版本：
<img width="473" alt="image" src="https://user-images.githubusercontent.com/26666273/228727392-c6b9ac54-6485-4ac3-87df-212a25441f1e.png">


麻烦您再看一下是不是Skip loading导致的。

**Comment by zkyseu** [comment]
@ChenSi521 我收到您的问题邮件了，这个和skip load没有关系，这部分权重就是不导入的，您需要在您的配置文件中加上`seg=False` ,如果不加的话会默认模型是分割模型而不是关键点模型。以下是我测试成功的配置文件

```
model = dict(
    name='Detector',
)

backbone = dict(
    name='ResNetWrapper',
    resnet='resnet50',
    pretrained=True,
    replace_stride_with_dilation=[False, False, False],
    out_conv=False,
    in_channels=[64, 128, 256, 512]
)

sample_y = range(590, 270, -8)

batch_size = 16
aggregator = dict(
    name='TransConvEncoderModule',
    in_dim=2048,
    attn_in_dims=[2048, 256],
    attn_out_dims=[256, 256],
    strides=[1, 1],
    ratios=[4, 4],
    pos_shape=(batch_size, 10, 25),
)

neck=dict(
    name='FPN',
    in_channels=[256, 512, 1024, 256],
    out_channels=64,
    num_outs=4,
    #trans_idx=-1,
)

loss_weights=dict(
        hm_weight=1,
        kps_weight=0.4,
        row_weight=1.,
        range_weight=1.,
    )

num_lane_classes=1
heads=dict(
    name='CondLaneHead',
    heads=dict(hm=num_lane_classes),
    in_channels=(64, ),
    num_classes=num_lane_classes,
    head_channels=64,
    head_layers=1,
    disable_coords=False,
    branch_in_channels=64,
    branch_channels=64,
    branch_out_channels=64,
    reg_branch_channels=64,
    branch_num_conv=1,
    hm_idx=2,
    mask_idx=0,
    compute_locations_pre=True,
    location_configs=dict(size=(batch_size, 1, 80, 200), device='cuda:0'),
    crit_loss = dict(name = 'Condlane_focalLoss'),
    crit_kp_loss = dict(name = 'RegL1KpLoss'),
    crit_ce_loss = dict(name = 'CrossEntropyLoss_nn')
    
)

epochs = 16
total_iter = (88880 // batch_size) * epochs

lr_scheduler = dict(
    name = 'MultiStepDecay',
    learning_rate = 3e-4,
    milestones=[8,14], 
    gamma=0.1
)

optimizer = dict(name='AdamW',  
                 beta1 =  0.9,
                 beta2 = 0.999, 
                 epsilon=1e-8)

seg_loss_weight = 1.0
eval_ep = 1
save_ep = 1 

img_norm = dict(
    mean=[0.295, 0.300, 0.304],
    std=[0.198, 0.211, 0.213]
)

img_height = 320 
img_width = 800
cut_height = 0 
ori_img_h = 590
ori_img_w = 1640

mask_down_scale = 4
hm_down_scale = 16
num_lane_classes = 1
line_width = 3
radius = 6
nms_thr = 4
img_scale = (800, 320)
crop_bbox = [0, 270, 1640, 590]
mask_size = (1, 80, 200)

train_process = [
    dict(name='Alaug',
    transforms=[dict(name='Compose', params=dict(bboxes=False, keypoints=True, masks=False)),
    dict(
        name='Crop',
        x_min=crop_bbox[0],
        x_max=crop_bbox[2],
        y_min=crop_bbox[1],
        y_max=crop_bbox[3],
        p=1),
    dict(name='Resize', height=img_scale[1], width=img_scale[0], p=1),
    dict(
        name='OneOf',
        transforms=[
            dict(
                name='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                name='HueSaturationValue',
                hue_shift_limit=(-10, 10),
                sat_shift_limit=(-15, 15),
                val_shift_limit=(-10, 10),
                p=1.0),
        ],
        p=0.7),
    dict(name='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(
        name='OneOf',
        transforms=[
            dict(name='Blur', blur_limit=3, p=1.0),
            dict(name='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.2),
    dict(name='RandomBrightness', limit=0.2, p=0.6),
    dict(
        name='ShiftScaleRotate',
        shift_limit=0.1,
        scale_limit=(-0.2, 0.2),
        rotate_limit=10,
        border_mode=0,
        p=0.6),
    dict(
        name='RandomResizedCrop',
        height=img_scale[1],
        width=img_scale[0],
        scale=(0.8, 1.2),
        ratio=(1.7, 2.7),
        p=0.6),
    dict(name='Resize', height=img_scale[1], width=img_scale[0], p=1),]
    ),
    dict(name='CollectLane',
        down_scale=mask_down_scale,
        hm_down_scale=hm_down_scale,
        max_mask_sample=5,
        line_width=line_width,
        radius=radius,
        keys=['img', 'gt_hm'],
        meta_keys=[
            'gt_masks', 'mask_shape', 'hm_shape',
            'down_scale', 'hm_down_scale', 'gt_points'
        ]
    ),
    #dict(name='Resize', size=(img_width, img_height)),
    dict(name='Normalize', img_norm=img_norm),
    dict(name='ToTensor', keys=['img', 'gt_hm'], collect_keys=['img_metas']),
]


val_process = [
    dict(name='Alaug',
        transforms=[dict(name='Compose', params=dict(bboxes=False, keypoints=True, masks=False)),
            dict(name='Crop',
            x_min=crop_bbox[0],
            x_max=crop_bbox[2],
            y_min=crop_bbox[1],
            y_max=crop_bbox[3],
            p=1),
        dict(name='Resize', height=img_scale[1], width=img_scale[0], p=1)]
    ),
    #dict(name='Resize', size=(img_width, img_height)),
    dict(name='Normalize', img_norm=img_norm),
    dict(name='ToTensor', keys=['img']),
]

dataset_path = '/root/autodl-tmp/culane'
dataset = dict(
    train=dict(
        name='CULane',
        data_root=dataset_path,
        split='train',
        processes=train_process,
    ),
    val=dict(
        name='CULane',
        data_root=dataset_path,
        split='test',
        processes=val_process,
    ),
    test=dict(
        name='CULane',
        data_root=dataset_path,
        split='test',
        processes=val_process,
    )
)

log_config = dict(
    name = 'LogHook',
    interval = 50
    )

custom_config = [dict(
    name = 'EvaluateHook'
    )]

device = 'gpu'
seed =  0
save_inference_dir = './inference'
output_dir = './output_dir'
best_dir = './output_dir/best_dir'
pred_save_dir = './pred_save'
num_workers = 4
view = False
ignore_label = 255
seg = False #这里需要加上这行代码才可以正常运行
```

**Comment by ChenSi521** [comment]
后来我也跑通了，感谢感谢！

**Comment by zkyseu** [comment]
我先关闭这个issue了哈，如果您有任何问题欢迎重新打开issue
